version: "2"
run:
  modules-download-mode: vendor
  tests: false
linters:
  default: none
  enable:
    - dupl
    - errcheck
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - wsl_v5
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - wrapperFunc
        - importShadow
        - unnamedResult
        - paramTypeCombine
        - emptyStringTest
        - nestingReduce
        - elseif
        - ifElseChain
        - whyNoLint
        - unnecessaryDefer
      enabled-tags:
        - performance
        - style
        - experimental
    gocyclo:
      min-complexity: 15
    govet:
      enable:
        - shadow
    lll:
      line-length: 120
    misspell:
      locale: US
    revive:
      confidence: 0
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$