// Code generated by "enumer -type=AccountStatus -text -json -transform=lower -trimprefix=AccountStatus -output=account_status_enum.go"; DO NOT EDIT.

package invest

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _AccountStatusName = "unspecifiedopenclosednew"

var _AccountStatusIndex = [...]uint8{0, 11, 15, 21, 24}

const _AccountStatusLowerName = "unspecifiedopenclosednew"

func (i AccountStatus) String() string {
	if i < 0 || i >= AccountStatus(len(_AccountStatusIndex)-1) {
		return fmt.Sprintf("AccountStatus(%d)", i)
	}
	return _AccountStatusName[_AccountStatusIndex[i]:_AccountStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AccountStatusNoOp() {
	var x [1]struct{}
	_ = x[AccountStatusUnspecified-(0)]
	_ = x[AccountStatusOpen-(1)]
	_ = x[AccountStatusClosed-(2)]
	_ = x[AccountStatusNew-(3)]
}

var _AccountStatusValues = []AccountStatus{AccountStatusUnspecified, AccountStatusOpen, AccountStatusClosed, AccountStatusNew}

var _AccountStatusNameToValueMap = map[string]AccountStatus{
	_AccountStatusName[0:11]:       AccountStatusUnspecified,
	_AccountStatusLowerName[0:11]:  AccountStatusUnspecified,
	_AccountStatusName[11:15]:      AccountStatusOpen,
	_AccountStatusLowerName[11:15]: AccountStatusOpen,
	_AccountStatusName[15:21]:      AccountStatusClosed,
	_AccountStatusLowerName[15:21]: AccountStatusClosed,
	_AccountStatusName[21:24]:      AccountStatusNew,
	_AccountStatusLowerName[21:24]: AccountStatusNew,
}

var _AccountStatusNames = []string{
	_AccountStatusName[0:11],
	_AccountStatusName[11:15],
	_AccountStatusName[15:21],
	_AccountStatusName[21:24],
}

// AccountStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AccountStatusString(s string) (AccountStatus, error) {
	if val, ok := _AccountStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AccountStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AccountStatus values", s)
}

// AccountStatusValues returns all values of the enum
func AccountStatusValues() []AccountStatus {
	return _AccountStatusValues
}

// AccountStatusStrings returns a slice of all String values of the enum
func AccountStatusStrings() []string {
	strs := make([]string, len(_AccountStatusNames))
	copy(strs, _AccountStatusNames)
	return strs
}

// IsAAccountStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AccountStatus) IsAAccountStatus() bool {
	for _, v := range _AccountStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for AccountStatus
func (i AccountStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for AccountStatus
func (i *AccountStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("AccountStatus should be a string, got %s", data)
	}

	var err error
	*i, err = AccountStatusString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for AccountStatus
func (i AccountStatus) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for AccountStatus
func (i *AccountStatus) UnmarshalText(text []byte) error {
	var err error
	*i, err = AccountStatusString(string(text))
	return err
}
