// Code generated by "enumer -type=Type -text -json -yaml -transform=lower -trimprefix=Type -output=type_enum.go"; DO NOT EDIT.

package instrument

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _TypeName = "unknownsharebondcurrencyetf"

var _TypeIndex = [...]uint8{0, 7, 12, 16, 24, 27}

const _TypeLowerName = "unknownsharebondcurrencyetf"

func (i Type) String() string {
	if i < 0 || i >= Type(len(_TypeIndex)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _TypeName[_TypeIndex[i]:_TypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TypeNoOp() {
	var x [1]struct{}
	_ = x[TypeUnknown-(0)]
	_ = x[TypeShare-(1)]
	_ = x[TypeBond-(2)]
	_ = x[TypeCurrency-(3)]
	_ = x[TypeETF-(4)]
}

var _TypeValues = []Type{TypeUnknown, TypeShare, TypeBond, TypeCurrency, TypeETF}

var _TypeNameToValueMap = map[string]Type{
	_TypeName[0:7]:        TypeUnknown,
	_TypeLowerName[0:7]:   TypeUnknown,
	_TypeName[7:12]:       TypeShare,
	_TypeLowerName[7:12]:  TypeShare,
	_TypeName[12:16]:      TypeBond,
	_TypeLowerName[12:16]: TypeBond,
	_TypeName[16:24]:      TypeCurrency,
	_TypeLowerName[16:24]: TypeCurrency,
	_TypeName[24:27]:      TypeETF,
	_TypeLowerName[24:27]: TypeETF,
}

var _TypeNames = []string{
	_TypeName[0:7],
	_TypeName[7:12],
	_TypeName[12:16],
	_TypeName[16:24],
	_TypeName[24:27],
}

// TypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TypeString(s string) (Type, error) {
	if val, ok := _TypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Type values", s)
}

// TypeValues returns all values of the enum
func TypeValues() []Type {
	return _TypeValues
}

// TypeStrings returns a slice of all String values of the enum
func TypeStrings() []string {
	strs := make([]string, len(_TypeNames))
	copy(strs, _TypeNames)
	return strs
}

// IsAType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Type) IsAType() bool {
	for _, v := range _TypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Type
func (i Type) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Type
func (i *Type) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Type should be a string, got %s", data)
	}

	var err error
	*i, err = TypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for Type
func (i Type) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Type
func (i *Type) UnmarshalText(text []byte) error {
	var err error
	*i, err = TypeString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for Type
func (i Type) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for Type
func (i *Type) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = TypeString(s)
	return err
}
